[package]
name = "rsground-runner"
version = "0.1.0"
description = "The runner engine for RsGround"
edition = "2021"
authors = ["Apika Luca"]

[lib]
test = true

[dependencies]
async-io = "2.4.1"
hakoniwa = { version = "1.7.2", features = ["landlock"] }
lsp-types = "0.97.0"
thiserror.workspace = true
tokio.workspace = true
log = "0.4"
uuid = { version = "1.16.0", features = ["v4"] }
